#define DYNAMIC_KEYMAP_LAYER_COUNT 5
#define TAPPING_TOGGLE 2

#define MOUSEKEY_MAX_SPEED 7
#define MOUSEKEY_MOVE_DELTA 3
#define MOUSEKEY_WHEEL_MAX_SPEED 3

#define AUTO_SHIFT_TIMEOUT 200
#define NO_AUTO_SHIFT_NUMERIC