#define DYNAMIC_KEYMAP_LAYER_COUNT 6

#define TAPPING_TOGGLE 2
// #define TAPPING_TERM 1000
// #define PERMISSIVE_HOLD
// #define IGNORE_MOD_TAP_INTERRUPT
// #define QUICK_TAP_TERM 0

#define MOUSEKEY_MAX_SPEED 7
#define MOUSEKEY_MOVE_DELTA 3
#define MOUSEKEY_WHEEL_MAX_SPEED 3

#define AUTO_SHIFT_TIMEOUT 300
#define NO_AUTO_SHIFT_NUMERIC
#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD

#define RGB_MATRIX_KEYPRESSES